# numpy

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [3]:
#creating an array
x=np.array([[1,4,6],[8,9,5]])
x

array([[1, 4, 6],
       [8, 9, 5]])

In [4]:
np.shape(x)

(2, 3)

In [5]:
np.size(x)

6

In [6]:
x.itemsize

4

In [7]:
#reshape
x.reshape(3,2)

array([[1, 4],
       [6, 8],
       [9, 5]])

In [8]:
x.reshape(1,6)

array([[1, 4, 6, 8, 9, 5]])

In [9]:
#slicing
x[0]

array([1, 4, 6])

In [10]:
x[0,1]

4

In [11]:
x[1,1]

9

In [18]:
x

array([[1, 4, 6],
       [8, 9, 5]])

In [22]:
x[:,-1]

array([6, 5])

In [23]:
x[:,0:2]

array([[1, 4],
       [8, 9]])

In [24]:
s=np.array([[1,4,6],[8,9,5],[8,6,4]])
s

array([[1, 4, 6],
       [8, 9, 5],
       [8, 6, 4]])

In [31]:
s[0:,::2]

array([[1, 6],
       [8, 5],
       [8, 4]])

In [33]:
s[1]

array([8, 9, 5])

In [34]:
s[0:2,0:2]

array([[1, 4],
       [8, 9]])

In [35]:
s

array([[1, 4, 6],
       [8, 9, 5],
       [8, 6, 4]])

In [36]:
#max and min
s.min()

1

In [37]:
s.sum()

51

In [38]:
s.mean()

5.666666666666667

In [42]:
s.sum(axis=0)

array([17, 19, 15])

In [43]:
s.sum(axis=1)

array([11, 22, 18])

In [44]:
np.sqrt(s)

array([[1.        , 2.        , 2.44948974],
       [2.82842712, 3.        , 2.23606798],
       [2.82842712, 2.44948974, 2.        ]])

In [45]:
np.std(s)

2.3570226039551585

## Vertical & Horizontal Stacking

In [54]:
a=np.array([[1,4,5],[4,7,8],[6,9,0]])
b=np.array([[1,7,4],[3,8,4],[1,8,4]])
np.vstack((a,b))

array([[1, 4, 5],
       [4, 7, 8],
       [6, 9, 0],
       [1, 7, 4],
       [3, 8, 4],
       [1, 8, 4]])

In [55]:
np.hstack((a,b))

array([[1, 4, 5, 1, 7, 4],
       [4, 7, 8, 3, 8, 4],
       [6, 9, 0, 1, 8, 4]])

In [56]:
np.ravel((a,b))

array([1, 4, 5, 4, 7, 8, 6, 9, 0, 1, 7, 4, 3, 8, 4, 1, 8, 4])

In [57]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
for i in np.arange(1,5):
    print(s)

[[1 4 6]
 [8 9 5]
 [8 6 4]]
[[1 4 6]
 [8 9 5]
 [8 6 4]]
[[1 4 6]
 [8 9 5]
 [8 6 4]]
[[1 4 6]
 [8 9 5]
 [8 6 4]]


In [60]:
np.sin(s)

array([[ 0.84147098, -0.7568025 , -0.2794155 ],
       [ 0.98935825,  0.41211849, -0.95892427],
       [ 0.98935825, -0.2794155 , -0.7568025 ]])

In [61]:
np.cos(s)

array([[ 0.54030231, -0.65364362,  0.96017029],
       [-0.14550003, -0.91113026,  0.28366219],
       [-0.14550003,  0.96017029, -0.65364362]])

# pandas

In [5]:
import pandas as pd

In [6]:
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [7]:
#creating a series data type

In [8]:
s=pd.Series([1,6,7,3,34,6])

In [9]:
s

0     1
1     6
2     7
3     3
4    34
5     6
dtype: int64

In [10]:
s1=pd.Series([1,6,7,3,34,6],index=['p','s','r','d','g','b'])

In [11]:

s1

p     1
s     6
r     7
d     3
g    34
b     6
dtype: int64

In [12]:
s+s1

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
b   NaN
d   NaN
g   NaN
p   NaN
r   NaN
s   NaN
dtype: float64

In [13]:
v1=[1,6,8,4]
v2=[6,9,9,2]
df=pd.DataFrame({'x':v1,'y':v2})
df

x  y
0  1  6
1  6  9
2  8  9
3  4  2

In [14]:
df

x  y
0  1  6
1  6  9
2  8  9
3  4  2

In [15]:
df.isnull()

x      y
0  False  False
1  False  False
2  False  False
3  False  False

# pandas operations:
>.slicing
> .merging
> .concatination
> .changing the index
> .changing column headers
> .data munging

In [16]:
df1=pd.DataFrame({'x':[55,99,77,55],'y':[7,5,3,2]},index=['a','b','c','d'],dtype=float)

In [17]:
df1

x    y
a  55.0  7.0
b  99.0  5.0
c  77.0  3.0
d  55.0  2.0

### column change

In [18]:
data=[[2,4,3,3],[12,5,5]]

In [19]:
df=pd.DataFrame(data,columns=["x1","x2","x3","x4"])

In [20]:
df

x1  x2  x3   x4
0   2   4   3  3.0
1  12   5   5  NaN

In [21]:
df.isnull()

x1     x2     x3     x4
0  False  False  False  False
1  False  False  False   True

In [22]:
df.values

array([[ 2.,  4.,  3.,  3.],
       [12.,  5.,  5., nan]])

In [23]:
df.size

8

In [24]:
df.shape

(2, 4)

In [25]:
df

x1  x2  x3   x4
0   2   4   3  3.0
1  12   5   5  NaN

# slicing 

In [26]:
df.tail()

x1  x2  x3   x4
0   2   4   3  3.0
1  12   5   5  NaN

# merging and joining

In [27]:
data=[[2,4,5],[9,4,3],[3,5,5,6]]
df=pd.DataFrame(data,columns=["x1","x2","x3","x4"])

In [28]:
df

x1  x2  x3   x4
0   2   4   5  NaN
1   9   4   3  NaN
2   3   5   5  6.0

In [43]:
df1

x    y
a  55.0  7.0
b  99.0  5.0
c  77.0  3.0
d  55.0  2.0

In [44]:
m=pd.merge(df1,df)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [45]:
m

x1  x2  x3  x4
0   1   3  23 NaN

In [46]:
j=df1.join(df)

In [33]:
df

x1  x2  x3   x4
0   2   4   5  NaN
1   9   4   3  NaN
2   3   5   5  6.0

In [34]:
df1

x    y
a  55.0  7.0
b  99.0  5.0
c  77.0  3.0
d  55.0  2.0

In [35]:
d=[[1,23,3],[1,4,5,6],[1,3,4,5],[1,3,23]]

In [36]:
f1=pd.DataFrame(d,columns=["x1","x2","x3","x4"])

In [37]:
f1

x1  x2  x3   x4
0   1  23   3  NaN
1   1   4   5  6.0
2   1   3   4  5.0
3   1   3  23  NaN

In [38]:
d1=[[5,5,4],[3,5,2,2],[1,3,23]]


In [39]:
f2=pd.DataFrame(d1,columns=["x1","x2","x3","x4"])
f2

x1  x2  x3   x4
0   5   5   4  NaN
1   3   5   2  2.0
2   1   3  23  NaN

In [40]:
m=pd.merge(f1,f2)
m

x1  x2  x3  x4
0   1   3  23 NaN

In [177]:
x=[[1,5,8],[8,9,5]]
f3=pd.DataFrame(x,columns=['y1','y2','y3'],index=['a','b'])

In [178]:
f4=pd.DataFrame({'name':[2,6,7],'gender':[1,5,6]})
f4

name  gender
0     2       1
1     6       5
2     7       6

In [179]:
joint=f3.join(f4)

In [180]:
joint

y1  y2  y3  name  gender
a   1   5   8   NaN     NaN
b   8   9   5   NaN     NaN

# concat

In [181]:
c=pd.concat([f3,f2])
c

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


x1   x2    x3   x4   y1   y2   y3
a  NaN  NaN   NaN  NaN  1.0  5.0  8.0
b  NaN  NaN   NaN  NaN  8.0  9.0  5.0
0  5.0  5.0   4.0  NaN  NaN  NaN  NaN
1  3.0  5.0   2.0  2.0  NaN  NaN  NaN
2  1.0  3.0  23.0  NaN  NaN  NaN  NaN

In [182]:
c.notnull()

x1     x2     x3     x4     y1     y2     y3
a  False  False  False  False   True   True   True
b  False  False  False  False   True   True   True
0   True   True   True  False  False  False  False
1   True   True   True   True  False  False  False
2   True   True   True  False  False  False  False

In [183]:
c.isnull()

x1     x2     x3     x4     y1     y2     y3
a   True   True   True   True  False  False  False
b   True   True   True   True  False  False  False
0  False  False  False   True   True   True   True
1  False  False  False  False   True   True   True
2  False  False  False   True   True   True   True

In [184]:
c.columns

Index(['x1', 'x2', 'x3', 'x4', 'y1', 'y2', 'y3'], dtype='object')

In [185]:
c["y2"]

a    5.0
b    9.0
0    NaN
1    NaN
2    NaN
Name: y2, dtype: float64

# changing the index

In [188]:
c1=pd.DataFrame({1:[1,2,3],2:[7,9,5],'i':['x','y','z']})
c1.set_index('i')

1  2
i      
x  1  7
y  2  9
z  3  5

# changing column headers

In [192]:
c2=c1.rename(columns={1:'a',2:'b'})
c2

a  b  i
0  1  7  x
1  2  9  y
2  3  5  z

In [193]:
c1

1  2  i
0  1  7  x
1  2  9  y
2  3  5  z

# Data munging

In [201]:
dd=pd.read_csv("table.csv")

In [202]:
dd

x  y
0  2  5
1  6  9
2  9  0