In [1]:
#elements acessing row/column
# loc and iloc--->location and index location based


In [2]:
import pandas as pd
df=pd.DataFrame({"name":['veena','kpr','praveena'],"roll-numbers":[455,427,323],"branch":["cse","ece","eee"]})

In [3]:
df

name  roll-numbers branch
0     veena           455    cse
1       kpr           427    ece
2  praveena           323    eee

In [4]:
import pandas as pd
df=pd.DataFrame({"name":['veena','kpr','praveena'],"roll-numbers":[455,427,323],"branch":["cse","ece","eee"]},index=[1,2,3])
                                                                                                              #index change

In [5]:
df

name  roll-numbers branch
1     veena           455    cse
2       kpr           427    ece
3  praveena           323    eee

In [6]:
df.loc[1]

name            veena
roll-numbers      455
branch            cse
Name: 1, dtype: object

In [7]:
df.loc[2]["roll-numbers"]

427

In [8]:
df.iloc[0]

name            veena
roll-numbers      455
branch            cse
Name: 1, dtype: object

In [9]:
df.iloc[2]["branch"]

'eee'

In [10]:
df

name  roll-numbers branch
1     veena           455    cse
2       kpr           427    ece
3  praveena           323    eee

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3 entries, 1 to 3
Data columns (total 3 columns):
name            3 non-null object
roll-numbers    3 non-null int64
branch          3 non-null object
dtypes: int64(1), object(2)
memory usage: 176.0+ bytes


In [12]:
df.describe()

roll-numbers
count      3.000000
mean     401.666667
std       69.550941
min      323.000000
25%      375.000000
50%      427.000000
75%      441.000000
max      455.000000

In [13]:
df.count()

name            3
roll-numbers    3
branch          3
dtype: int64

In [14]:
df.dtypes


name            object
roll-numbers     int64
branch          object
dtype: object

In [15]:
df.count(axis="rows")          #rows=1 

name            3
roll-numbers    3
branch          3
dtype: int64

In [16]:
df.count(axis=1)

1    3
2    3
3    3
dtype: int64

In [17]:
df.count(axis="columns")

1    3
2    3
3    3
dtype: int64

In [18]:
df.count(axis=0)

name            3
roll-numbers    3
branch          3
dtype: int64

In [19]:
df

name  roll-numbers branch
1     veena           455    cse
2       kpr           427    ece
3  praveena           323    eee

In [20]:
df.set_index(["roll-numbers"])

name branch
roll-numbers                 
455              veena    cse
427                kpr    ece
323           praveena    eee

In [21]:
df.set_index(["branch"])

name  roll-numbers
branch                        
cse        veena           455
ece          kpr           427
eee     praveena           323

In [22]:
df.set_index(["roll-numbers","branch"])

name
roll-numbers branch          
455          cse        veena
427          ece          kpr
323          eee     praveena

In [23]:
frame=pd.Series([4,4,2,5,7,"none"])
frame

0       4
1       4
2       2
3       5
4       7
5    none
dtype: object

In [24]:
frame.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [25]:
frame.describe()

count     6
unique    5
top       4
freq      2
dtype: int64

In [26]:
frame.count()

6

In [27]:
import numpy as np

In [28]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
data=pd.DataFrame(np.arange(12))

In [32]:
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11

In [33]:
data=pd.DataFrame(np.arange(12).reshape(4,3))

In [34]:
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [35]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c'])

In [36]:
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [37]:
x=np.arange(20)
x                                  #example

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
x.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [39]:
data=pd.DataFrame(np.arange(20))

In [40]:
data

0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19

In [41]:
data=pd.DataFrame(np.arange(12).reshape(4,3),columns=['a','b','c']) #columns=list('abc')

In [42]:
data

a   b   c
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [43]:
data.loc[1,'b']=np.NaN

In [44]:
data

a     b   c
0  0   1.0   2
1  3   NaN   5
2  6   7.0   8
3  9  10.0  11

In [45]:
data.isnull()

a      b      c
0  False  False  False
1  False   True  False
2  False  False  False
3  False  False  False

In [46]:
data.isnull().sum()

a    0
b    1
c    0
dtype: int64

In [47]:
df

name  roll-numbers branch
1     veena           455    cse
2       kpr           427    ece
3  praveena           323    eee

In [48]:
df+data

a   b branch   c name  roll-numbers
0 NaN NaN    NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN  NaN           NaN

In [49]:
dd=df.add(data)
dd

a   b branch   c name  roll-numbers
0 NaN NaN    NaN NaN  NaN           NaN
1 NaN NaN    NaN NaN  NaN           NaN
2 NaN NaN    NaN NaN  NaN           NaN
3 NaN NaN    NaN NaN  NaN           NaN

In [50]:
dd.add(data,fill_value=1)

a     b branch     c name  roll-numbers
0   1.0   2.0    NaN   3.0  NaN           NaN
1   4.0   NaN    NaN   6.0  NaN           NaN
2   7.0   8.0    NaN   9.0  NaN           NaN
3  10.0  11.0    NaN  12.0  NaN           NaN

In [51]:
dd.add(data,fill_value=9)

a     b branch     c name  roll-numbers
0   9.0  10.0    NaN  11.0  NaN           NaN
1  12.0   NaN    NaN  14.0  NaN           NaN
2  15.0  16.0    NaN  17.0  NaN           NaN
3  18.0  19.0    NaN  20.0  NaN           NaN

In [52]:
np.random.randn(2,5)

array([[ 0.0824649 , -1.60864851,  0.00356655, -0.58225808,  1.00672648],
       [ 1.85569758,  0.12691763,  0.23139943,  1.44135207,  0.16818245]])

In [53]:
np.random.rand(1,10)

array([[0.97637363, 0.209317  , 0.68696938, 0.83409565, 0.4295813 ,
        0.7678189 , 0.26901326, 0.74702143, 0.39567977, 0.94113948]])

## creating to dataframe with random values

In [54]:
r=pd.DataFrame(np.random.randn(3,4))
r

0         1         2         3
0  1.075472 -1.949305 -0.598876  0.380685
1  0.240266  1.344107 -0.882899  2.659070
2  0.264461  0.431720 -1.506453 -0.778244

In [55]:
r=pd.DataFrame(np.random.randn(3,4),index=['a','b','c'])
r                                                           # insert index

0         1         2         3
a  0.915679 -0.920118  0.184398  0.189955
b  0.633627 -0.909371  0.298453  0.534474
c  0.677968  2.215783 -1.356797  0.568692

In [56]:
r=pd.DataFrame(np.random.randn(3,4),index=['a','b','c'],columns=['s1','s2','s3','s4'])
r         # insert columns---------->r.index=

s1        s2        s3        s4
a -0.484005 -0.695807  1.004375  1.299229
b  0.762190  1.396149  1.150490 -1.194819
c  0.333777  1.129958  1.540155  0.260702

### reindexing

In [57]:
r1=r.reindex(['b','p','c','m'])
r1

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
p       NaN       NaN       NaN       NaN
c  0.333777  1.129958  1.540155  0.260702
m       NaN       NaN       NaN       NaN

In [58]:
r1.isnull()

s1     s2     s3     s4
b  False  False  False  False
p   True   True   True   True
c  False  False  False  False
m   True   True   True   True

In [59]:
r1.isnull().sum()

s1    2
s2    2
s3    2
s4    2
dtype: int64

In [60]:
r1.dropna()    #to remove null value(or)dropping the null values

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
c  0.333777  1.129958  1.540155  0.260702

In [61]:
r1.fillna(5)   #to fill a value in null place

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
p  5.000000  5.000000  5.000000  5.000000
c  0.333777  1.129958  1.540155  0.260702
m  5.000000  5.000000  5.000000  5.000000

In [62]:
# fill in backword 
r1.fillna(method='bfill',axis=0).fillna(1)

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
p  0.333777  1.129958  1.540155  0.260702
c  0.333777  1.129958  1.540155  0.260702
m  1.000000  1.000000  1.000000  1.000000

In [63]:
# fill in forword 
r1.fillna(method='ffill',axis=0).fillna(1)      #ffill-->forward

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
p  0.762190  1.396149  1.150490 -1.194819
c  0.333777  1.129958  1.540155  0.260702
m  0.333777  1.129958  1.540155  0.260702

In [64]:
r1.isna()         #null place is true

s1     s2     s3     s4
b  False  False  False  False
p   True   True   True   True
c  False  False  False  False
m   True   True   True   True

In [65]:
r1.isnull()

s1     s2     s3     s4
b  False  False  False  False
p   True   True   True   True
c  False  False  False  False
m   True   True   True   True

In [66]:
pd.isna(r1['s1']) #particular data null or not

b    False
p     True
c    False
m     True
Name: s1, dtype: bool

### DATA REPLACING

In [67]:
r1

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
p       NaN       NaN       NaN       NaN
c  0.333777  1.129958  1.540155  0.260702
m       NaN       NaN       NaN       NaN

In [68]:
df33=pd.DataFrame({11:[5,8,4],12:[2,6,22],13:[3,5,6]})
df33

11  12  13
0   5   2   3
1   8   6   5
2   4  22   6

In [69]:
df33.replace(4,777)

11  12  13
0    5   2   3
1    8   6   5
2  777  22   6

In [70]:
df33.replace([2,7,45],3422222222222)

11             12  13
0   5  3422222222222   3
1   8              6   5
2   4             22   6

In [71]:
df33.replace([233,46,5],[3,5,5])

11  12  13
0   5   2   3
1   8   6   5
2   4  22   6

In [72]:
df33.replace({2:44,3:4555})

11  12    13
0   5  44  4555
1   8   6     5
2   4  22     6

In [73]:
r1

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
p       NaN       NaN       NaN       NaN
c  0.333777  1.129958  1.540155  0.260702
m       NaN       NaN       NaN       NaN

In [74]:
#index sorting and ranking
r2=r1.reindex(['a','c','b','j'])
r2
r1

s1        s2        s3        s4
b  0.762190  1.396149  1.150490 -1.194819
p       NaN       NaN       NaN       NaN
c  0.333777  1.129958  1.540155  0.260702
m       NaN       NaN       NaN       NaN

In [75]:
r2.sort_index()

s1        s2        s3        s4
a       NaN       NaN       NaN       NaN
b  0.762190  1.396149  1.150490 -1.194819
c  0.333777  1.129958  1.540155  0.260702
j       NaN       NaN       NaN       NaN

In [76]:
r1.columns=['s4','s3','s2','s1']
r1

s4        s3        s2        s1
b  0.762190  1.396149  1.150490 -1.194819
p       NaN       NaN       NaN       NaN
c  0.333777  1.129958  1.540155  0.260702
m       NaN       NaN       NaN       NaN

In [77]:
r1.sort_index(axis=1)

s1        s2        s3        s4
b -1.194819  1.150490  1.396149  0.762190
p       NaN       NaN       NaN       NaN
c  0.260702  1.540155  1.129958  0.333777
m       NaN       NaN       NaN       NaN

### Groupby

In [78]:
animal_df=pd.DataFrame({'name':['dog','cat','cow','dog','cow'],'place':['zoo','park','zoo','ooo','ghh'],'feature':['ds','sdf','dsf','ds','sdf']})
animal_df

name place feature
0  dog   zoo      ds
1  cat  park     sdf
2  cow   zoo     dsf
3  dog   ooo      ds
4  cow   ghh     sdf

In [79]:
animal_df.groupby('name')

In [80]:
animal_df.groupby('name').sum()

place feature
name                
cat     park     sdf
cow   zooghh  dsfsdf
dog   zooooo    dsds

In [81]:
animal_df.groupby('name').count()

place  feature
name                
cat       1        1
cow       2        2
dog       2        2

In [82]:
animal_df.groupby(['name','feature']).sum()

place
name feature        
cat  sdf        park
cow  dsf         zoo
     sdf         ghh
dog  ds       zooooo

In [83]:
animal_df.groupby(['feature']).count()

name  place
feature             
ds          2      2
dsf         1      1
sdf         2      2

In [84]:
animal_df.groupby(['feature']).sum()

name    place
feature                 
ds       dogdog   zooooo
dsf         cow      zoo
sdf      catcow  parkghh

### RANKING

In [85]:
ani_df=pd.DataFrame({'name':['dog','cat','cow','dog','cow'],'place':['zoo','park','zoo','ooo','ghh'],'no-legs':[4,6,6,9,np.nan]})
ani_df

name place  no-legs
0  dog   zoo      4.0
1  cat  park      6.0
2  cow   zoo      6.0
3  dog   ooo      9.0
4  cow   ghh      NaN

In [86]:
ani_df["rank1"]=ani_df["no-legs"].rank()
ani_df

name place  no-legs  rank1
0  dog   zoo      4.0    1.0
1  cat  park      6.0    2.5
2  cow   zoo      6.0    2.5
3  dog   ooo      9.0    4.0
4  cow   ghh      NaN    NaN

In [87]:
ani_df["max-rank"]=ani_df["no-legs"].rank(method="max")  
ani_df                                                                    #max rank

name place  no-legs  rank1  max-rank
0  dog   zoo      4.0    1.0       1.0
1  cat  park      6.0    2.5       3.0
2  cow   zoo      6.0    2.5       3.0
3  dog   ooo      9.0    4.0       4.0
4  cow   ghh      NaN    NaN       NaN

In [88]:
ani_df["first-rank"]=ani_df["no-legs"].rank(method="first")  
ani_df                                                                #first rank

name place  no-legs  rank1  max-rank  first-rank
0  dog   zoo      4.0    1.0       1.0         1.0
1  cat  park      6.0    2.5       3.0         2.0
2  cow   zoo      6.0    2.5       3.0         3.0
3  dog   ooo      9.0    4.0       4.0         4.0
4  cow   ghh      NaN    NaN       NaN         NaN

In [89]:
ani_df["non-rank"]=ani_df["no-legs"].rank(na_option="bottom")  
ani_df                                                                #non rank

name place  no-legs  rank1  max-rank  first-rank  non-rank
0  dog   zoo      4.0    1.0       1.0         1.0       1.0
1  cat  park      6.0    2.5       3.0         2.0       2.5
2  cow   zoo      6.0    2.5       3.0         3.0       2.5
3  dog   ooo      9.0    4.0       4.0         4.0       4.0
4  cow   ghh      NaN    NaN       NaN         NaN       5.0

In [90]:
ani_df["pct-rank"]=ani_df["no-legs"].rank(pct=True)   #pictorial
ani_df

name place  no-legs  rank1  max-rank  first-rank  non-rank  pct-rank
0  dog   zoo      4.0    1.0       1.0         1.0       1.0     0.250
1  cat  park      6.0    2.5       3.0         2.0       2.5     0.625
2  cow   zoo      6.0    2.5       3.0         3.0       2.5     0.625
3  dog   ooo      9.0    4.0       4.0         4.0       4.0     1.000
4  cow   ghh      NaN    NaN       NaN         NaN       5.0       NaN

### categorise

In [91]:
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [92]:
data_frame["cc"]=data_frame['y'].astype('category')

In [93]:
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [94]:
data_frame["cc"]

0     6
1     7
2     8
3     9
4    10
Name: cc, dtype: category
Categories (5, int64): [6, 7, 8, 9, 10]

In [95]:
data_frame["cc"].cat.categories=["good","bad","worst","excellent","poor"]
data_frame

x   y         cc
0  1   6       good
1  2   7        bad
2  3   8      worst
3  4   9  excellent
4  5  10       poor

In [96]:
data_frame["cc"]=data_frame["cc"].set_categories=["good","bad","worst","excellent","poor"]
data_frame

x   y         cc
0  1   6       good
1  2   7        bad
2  3   8      worst
3  4   9  excellent
4  5  10       poor

In [97]:
data_frame.sort_values('cc')

x   y         cc
1  2   7        bad
3  4   9  excellent
0  1   6       good
4  5  10       poor
2  3   8      worst

In [98]:
data_frame.groupby("cc").sum()

x   y
cc              
bad        2   7
excellent  4   9
good       1   6
poor       5  10
worst      3   8

In [99]:
data_frame.groupby("cc").size()

cc
bad          1
excellent    1
good         1
poor         1
worst        1
dtype: int64

### reading the data

In [104]:
df=pd.read_table("sample.txt")

df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a b c
0  1 3 2
1  1 2 4
2  3 6 4

In [107]:
df=pd.read_table("ex1.csv")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [108]:
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [109]:
df=pd.read_table("ex2.csv")
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


1,2,3,4,hello
0   5,6,7,8,world
1  9,10,11,12,foo

In [110]:
df.head(1)

1,2,3,4,hello
0  5,6,7,8,world

In [111]:
df.tail(1)

1,2,3,4,hello
1  9,10,11,12,foo